### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by afichtenholtz** [andrej-fischer/cloneHD#17]
Running the example test set I run into a seg fault:
# ./build/filterHD --data ./test/data//normal.cna.txt --mode 3 --pre ./test/results//normal.cna

filterHD: Fitting jump-diffusion model to data at 20001 loci in 1 segment(s) in 1 sample(s) with a poisson emission model:

Filtering sample 1 of 1:
Initial range is 3.801e+01 < x < 8.500e+01
eval jump        sigma       rnd         -llh
  10 1.71212e-06 7.74107e-04 3.80764e-05 6.9367034070e+04
  20 3.49225e-08 7.03853e-04 1.87274e-04 6.9362282092e+04
  30 1.98473e-09 7.61654e-04 3.09235e-04 6.9361873946e+04
  40 1.07903e-09 7.62688e-04 7.27041e-05 6.9361621633e+04
Adapted range to 5.493e+01 < x < 6.526e+01
  10 1.32967e-09 7.25762e-04 2.95731e-05 6.9359987522e+04
  20 1.05477e-09 7.33552e-04 1.30669e-05 6.9359948984e+04
  30 1.03791e-09 7.37987e-04 9.48939e-07 6.9359941037e+04
Segmentation fault (core dumped)

**Comment by ivazquez** [comment]
Hi @afichtenholtz,

Which release version are you using? filterHD expects the `./test/results` directory to exist, so this may be the causing the segmentation fault.

Ignacio

**Comment by afichtenholtz** [comment]
Thanks Ignacio. Creating the results directory and ensuring access permission solved the problem.
