### ISSUE TITLE
Normal copy number error

### ISSUE THREAD

**Issue by afichtenholtz** [andrej-fischer/cloneHD#19]
Trying to do a basic run using run_example.sh as a template on whole exome data. Got as far as running cloneHD but was met with this error: 

"Normal copy number for some BAF data chromosomes is not 2."

Code inspection shows some sort of calculation for normal copy number from baf data? Not really sure how to proceed from here.

**Comment by ivazquez** [comment]
You might be having an issue with chr X/Y, what is the gender? Are you providing a normal copy number file with the cloneHD `--chr` flag?

**Comment by afichtenholtz** [comment]
Thanks for following up. The problem was that I wasn't specifying the normal copy number file with the --chr flag. The program can now proceed.

**Comment by Alxmertz** [comment]
Thank you guys. That solution fixed it!
