### ISSUE TITLE
simulated data availability for testing

### ISSUE THREAD

**Issue by hartmaier** [andrej-fischer/cloneHD#3]
The readme refers to running a test on simulated data but this data does not seem to be available.

**Comment by andrej-fischer** [comment]
Hi, the simulated data is only available within the [release](https://github.com/andrej-fischer/cloneHD/releases) packages. Please let me know if there is still a problem.

**Comment by hartmaier** [comment]
Thanks.  I found it now (in the cloneHD tarball).  (I had downloaded the MacOS build file and the source tarball files - both don't have the test data).
