### ISSUE TITLE
set fault on cloneHD snv mode with single-variant chroms

### ISSUE THREAD

**Issue by sinnweja** [andrej-fischer/cloneHD#4]
I have exome-only variants, so have some chromosomes with only 1 somatic variant. I recompiled with your latest bug fixes and still appear to be getting the seg fault. When I remove the single-variant chromosomes, no seg fault. Your help is appreciated, and we look forward to using this on more samples.

**Comment by andrej-fischer** [comment]
This sounds like a bug that should be already fixed in the master branch. Have you tried the release 1.17.8 or the master branch in the current state? If your error still appears, I would need a minimal data set to replicate the bug in order to debug.

**Comment by andrej-fischer** [comment]
Please re-open the issue if the problem reappears.
