### ISSUE TITLE
filterHD problem

### ISSUE THREAD

**Issue by dingxiaofan1** [andrej-fischer/cloneHD#6]
Great job.
But Sth wrong with filterHD. When I try to use filterHD to get the bias estimation, it says
Initial range is 1.010e+00 < x < 3.132e+03
eval jump sigma -llh
ERROR
Aborted (core dumped)
And no more information about this error. Then I think maybe sth wrong with my input. So I tested it with head -n. The funny thing is that, the program will prompt error at some line. But those lines looks good great than 0. Even if I removed all the 0s or change 0 to 1. The program still crashed. But when I split the segments into tiny segments and do the analysis, it sometimes works. So I really don't what's the problem.

Regards,

John

**Comment by andrej-fischer** [comment]
Hi John,

at first glance, this seems like a problem on the data side. In filterHD, the distribution of the hidden emission rate is approximated by their values on a finite grid (--grid option, default 100). The range/support of this distribution in [0,1] for (beta) binomial (mode 1/2), but it is chosen for Poisson to include the inner 99.8% of the data.  
What to do: (i) make sure that --rnd is not set to zero. (ii) pre filter your read depth data, e.g. with the pre-filter program.

**Comment by dingxiaofan1** [comment]
Yes. I just used the default rnd setting 0 in the example.sh. After changing its value, it works. Is there any suggestion on how to choose the value for rnd?

**Comment by andrej-fischer** [comment]
Hi, if you don't fix it via `--rnd [some number > 0]`, the optimal value is found automatically.

**Comment by dingxiaofan1** [comment]
Thanks.
